# Generated by Django 4.2.2 on 2023-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_place_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='explore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('imageUrl', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('cost', models.CharField(max_length=20)),
            ],
        ),
    ]
