# Generated by Django 4.2.2 on 2023-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_place_about_place_city_place_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explore',
            name='about',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='explore',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='explore',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
    ]
