# Generated by Django 4.2.2 on 2023-07-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explore',
            name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='place',
            name='imageUrl',
        ),
    ]
